---
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:arm64v8-8.0.28-ls33
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Johannesburg
      - MONGO_USER=${MONGO_USERNAME}
      - MONGO_PASS=${MONGO_PASSWORD}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_TLS= #optional
      - MONGO_AUTHSOURCE= #optional
    volumes:
      - ${UNIFI_DATA_DIR}:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
  unifi-db:
    image: mongodb-raspberrypi4-unofficial-r7.0.6
    container_name: unifi-db
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
